### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by kurtyks** [irontec/sngrep#534]
Hello,
while compiling sngrep on Fedora 43, I encountered the following build error:
```
address.c: In function ‘address_from_str’:
address.c:115:5: error: implicit declaration of function ‘sng_strncpy’; did you mean ‘strncpy’? [-Wimplicit-function-declaration]
  115 |     sng_strncpy(scanipport, ipport, sizeof(scanipport));
      |     ^~~~~~~~~~~
      |     strncpy
```
I confirmed, that the same error occurs on Debian trixie 

Build steps:
```
autoupdate
./bootstrap.sh
./configure --silent
make
```

System details:
```
Linux 5.14.0-611.13.1.el9_7.x86_64
gcc (GCC) 15.2.1 20260123 (Red Hat 15.2.1-7)
```

It appears that the function sng_strncpy() is implemented in util.c but is not declared in util.h. As a result, when compiling with newer GCC versions that treat implicit function declarations as errors, the build fails. As i see sng_strncpy() was added in v1.8.3 release, but that's odd, that no one else reported such issue, and that's suspicious... 

Adding the following declaration to util.h resolved the issue:
```
char *sng_strncpy(char *dst, const char *src, size_t n);
```

After applying this change, the project compiled cleanly without further issues on both - RHEL and Debian.

I will shortly submit a pull request with this fix. This issue is being opened as justification and context for that PR. 
I'm newbie, please don't kill me for mistakes

**Comment by kurtyks** [comment]
I digged deeper and just found out, that it is already resolved in this [PR](https://github.com/irontec/sngrep/pull/519) 
I'm closing this issue, no PR's from me, sorry for spam. 

Short update is, that I tried to work with code from **tag** v1.8.3, but that change was applied to **branch main**, with no new tag, so that explains why no one else reported that recently. All clear
