### PR TITLE
src/capture_openssl.h: fix build with libressl >= 3.5.0

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with libressl >= 3.5.0:

```
capture_openssl.c: In function 'P_hash':
capture_openssl.c:101:18: error: storage size of 'hm' isn't known
  101 |         HMAC_CTX hm;
      |                  ^~
```

Fixes:
 - http://autobuild.buildroot.org/results/f1e8cdb3ac35a30055ab79d41e6cc038e5339c37

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by Kaian** [comment]
Thanks!!
